import "@/public/assets/css/Dashboard.css";
import Providers from "@/components/Provider";
import Dashboard from "../../layouts/Dashboard";
import Sidebar from "@/components/dashboard/Sidebar";

export const metadata = {
  title: "Marble Dashboard",
  description: "Generated by Dev Adil",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body suppressHydrationWarning={true}>
        <Providers>
          <Sidebar />
          <main className="main-content-area">
          <Dashboard>
            {children}
            </Dashboard>
          </main>
        </Providers>
      </body>
    </html>
  );
}